name: dsfcrowdfunding_site_generator
description: A new Flutter project. 

publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0' 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  dsfcrowdfunding:
    git:
      url: https://github.com/igormidev/dsfcrowdfunding.git

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0 
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons: 
  image_path: "assets/app_logo.png" 
  web:
    generate: true 

flutter: 
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
