name: dsfcrowdfunding
description: Crowdfunding of DSF users.
version: 0.0.1 

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.5.0 
  flutter_credit_card: ^4.0.1
  flutter_svg: ^2.0.4
  qr_flutter: ^4.1.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  json_serializable: ^6.6.1
  provider: ^6.0.5
  chewie: ^1.7.1
  video_player: ^2.8.1 
  visibility_detector: ^0.4.0+2
  image_network: ^2.5.4+1
  dio: ^5.3.3
  freezed_annotation: ^2.0.3
  # video_player_web: ^2.1.2
  # video_player_web_hls: ^1.1.0 
  # video_player: ^2.7.0
  # video_player_web: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 
  freezed: ^2.0.3+1 
  build_runner: ^2.1.4

flutter: 
  plugin:
    platforms: 
      some_platform:
        pluginClass: somePluginClass

  uses-material-design: true
  fonts:
    - family: MangoGrotesque
      fonts:
        - asset: assets/fonts/MangoGrotesque/MangoGrotesque-Regular.ttf
          weight: 400
        - asset: assets/fonts/MangoGrotesque/MangoGrotesque-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MangoGrotesque/MangoGrotesque-Bold.ttf
          weight: 700
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo/Archivo-Thin.ttf
          weight: 100
        - asset: assets/fonts/Archivo/Archivo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Archivo/Archivo-Light.ttf
          weight: 300
        - asset: assets/fonts/Archivo/Archivo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Archivo/Archivo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo/Archivo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Archivo/Archivo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Archivo/Archivo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Archivo/Archivo-Black.ttf
          weight: 900
  assets:
    - assets/images/